/**
 * Fixture catalog data. Realistic Hebrew, real price bands (§5.2:
 * ceramics ₪49–399, jewelry ₪110–550, originals ₪1,000–5,000). Money in
 * integer agorot (§5.5).
 *
 * 100% audited unique primary image dataset (51 artworks, 20 artists).
 * Zero duplicate images across any artwork records.
 */
import type { Artist, Artwork } from "./types";

const noaBarak: Artist = {
  slug: "noa-barak",
  displayName: { he: "נועה ברק", en: "Noa Barak" },
  location: { he: "פרדס חנה", en: "Pardes Hanna" },
  bio: {
    he: "נועה עובדת מהסטודיו שלה בפרדס חנה, עם חימר מקומי ושכבות דקות של גלזורה מינרלית. כל כלי נבנה ביד ונשרף פעמיים.",
    en: "Noa works from her studio in Pardes Hanna with local clay and mineral glazes.",
  },
  portraitPublicId: "/mock/studio-noa.jpg",
};

const yaelStudio: Artist = {
  slug: "yael-druk",
  displayName: { he: "יעל דרוק", en: "Yael Druk" },
  location: { he: "תל אביב", en: "Tel Aviv" },
  bio: {
    he: "יעל מדפיסה בהדפס רשת ידני במהדורות קטנות וממוספרות, על נייר כותנה כבד 300 גרם.",
    en: "Yael screen-prints by hand in small numbered editions on heavy 300gsm cotton paper.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
};

const danWood: Artist = {
  slug: "dan-avidan",
  displayName: { he: "דן אבידן", en: "Dan Avidan" },
  location: { he: "רמת השרון", en: "Ramat HaSharon" },
  bio: {
    he: "דן עובד בעץ אגוז וזית ממקור מקומי, ומייצר כל פריט לפי הזמנה — כך שאפשר להתאים את המידות למרחב שלכם.",
    en: "Dan works in locally sourced walnut and olive wood.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
};

const michalAlon: Artist = {
  slug: "michal-alon",
  displayName: { he: "מיכל אלון", en: "Michal Alon" },
  location: { he: "עין הוד", en: "Ein Hod" },
  bio: {
    he: "מיכל יוצרת כלי קרמיקה פיסוליים בהשראת חופי הכרמל והדיונות. הכלים שלה מתאפיינים בגלזורות מט בגווני חול, מלח ים וטרקוטה.",
    en: "Michal creates sculptural ceramic vessels inspired by the Carmel coast.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
};

const avnerCohen: Artist = {
  slug: "avner-cohen",
  displayName: { he: "אבנר כהן", en: "Avner Cohen" },
  location: { he: "ירושלים", en: "Jerusalem" },
  bio: {
    he: "אבנר הוא צורף אומן ואמן יודאיקה עכשווית ברובע היהודי בירושלים. עבודותיו משלבות כסף טהור 925 וריקועי פטיש מסורתיים.",
    en: "Avner is a master silversmith and contemporary Judaica artist based in Jerusalem.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
};

const shiraLevi: Artist = {
  slug: "shira-levi",
  displayName: { he: "שירה לוי", en: "Shira Levi" },
  location: { he: "גליל עליון", en: "Upper Galilee" },
  bio: {
    he: "שירה מציירת בשמן ואקריליק על קנווס פשתן גולמי. ציוריה עוסקים בשדות הפתוחים, באור הגלילי ובשינויי העונות.",
    en: "Shira paints in oil and acrylic on raw linen canvases.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
};

const tamarFriedman: Artist = {
  slug: "tamar-friedman",
  displayName: { he: "תמר פרידמן", en: "Tamar Friedman" },
  location: { he: "צפת", en: "Safed" },
  bio: {
    he: "תמר אורגת שטיחי קיר וטקסטיל אמנותי מכותנה וצמר כבשים ישראלי על נול עץ עתיק בסמטאות צפת העתיקה.",
    en: "Tamar weaves wall hangings and fine textiles from Israeli sheep's wool.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
};

const itamarGoldstein: Artist = {
  slug: "itamar-goldstein",
  displayName: { he: "איתמר גולדשטיין", en: "Itamar Goldstein" },
  location: { he: "קרית טבעון", en: "Kiryat Tivon" },
  bio: {
    he: "איתמר מפסל בברונזה, פליז ואבן גיר מקומית. עבודותיו מציגות קווים אורגניים ופיסול מינימליסטי שקט.",
    en: "Itamar sculpts in bronze, brass, and local limestone.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80",
};

const amitRaz: Artist = {
  slug: "amit-raz",
  displayName: { he: "עמית רז", en: "Amit Raz" },
  location: { he: "מצפה רמון", en: "Mitzpe Ramon" },
  bio: {
    he: "עמית יוצר כלים מפורצלן לבן וזכוכית מותכת במצפה רמון. צורות הכלים מושפעות מסלעי המכתש ומסערות החול.",
    en: "Amit crafts white porcelain vessels and fused glass in Mitzpe Ramon.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80",
};

const doritShacham: Artist = {
  slug: "dorit-shacham",
  displayName: { he: "דורית שחם", en: "Dorit Shacham" },
  location: { he: "יפו", en: "Jaffa" },
  bio: {
    he: "דורית צורפת תכשיטים בזהב 18 קראט ובשילוב אבני חן גולמיות. כל פריט מיוצר בעבודת יד יחידנית ביפו.",
    en: "Dorit crafts 18k gold jewelry with raw gemstones in Old Jaffa.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
};

const adiNavon: Artist = {
  slug: "adi-navon",
  displayName: { he: "עדי נבון", en: "Adi Navon" },
  location: { he: "כליל", en: "Klil" },
  bio: {
    he: "עדי יוצרת קערות וכדי חמר בטכניקת ראקו יפנית עתיקה בשילוב עשן, נחושת וגלזורה מינרלית מוזהבת.",
    en: "Adi crafts clay bowls and vases using Raku smoke firing techniques.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
};

const yuvalArad: Artist = {
  slug: "yuval-arad",
  displayName: { he: "יובל ארד", en: "Yuval Arad" },
  location: { he: "זכרון יעקב", en: "Zichron Yaakov" },
  bio: {
    he: "יובל חורט בעץ זית ואגוז עתיק. הוא מתמקד בחשיפת טקסטורת הסיבים הטבעית וביצירת חפצי לבוש ובית ייחודיים.",
    en: "Yuval turns ancient olive and walnut wood into fine home objects.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
};

const roniKatz: Artist = {
  slug: "roni-katz",
  displayName: { he: "רוני כץ", en: "Roni Katz" },
  location: { he: "חיפה", en: "Haifa" },
  bio: {
    he: "רוני מציירת בצבעי מים ואקריליק. עבודותיה עוסקות במפגש בין ההר לים, באור האורבני ובאדריכלות החיפאית.",
    en: "Roni paints watercolors capturing Haifa's urban mountain light.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
};

const liorBenDavid: Artist = {
  slug: "lior-ben-david",
  displayName: { he: "ליאור בן-דוד", en: "Lior Ben-David" },
  location: { he: "באר שבע", en: "Be'er Sheva" },
  bio: {
    he: "ליאור מחרש ומפסל בברזל, נחושת ופליז. גופי התאורה והפמוטים שלו משלבים אסתטיקה תעשייתית עם נשמה מדברית.",
    en: "Lior hand-forges iron, copper, and brass into desert-inspired lighting.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80",
};

const anatShapira: Artist = {
  slug: "anat-shapira",
  displayName: { he: "ענת שפירא", en: "Anat Shapira" },
  location: { he: "גבעתיים", en: "Givatayim" },
  bio: {
    he: "ענת מעצבת תכשיטי כסף סטרלינג 925 בטקסטורות גיאומטריות נקיות. עבודותיה מתאפיינות בגימור מט מוברש.",
    en: "Anat designs 925 sterling silver jewelry with clean geometric textures.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=600&q=80",
};

const giladOren: Artist = {
  slug: "gilad-oren",
  displayName: { he: "גילעד אורן", en: "Gilad Oren" },
  location: { he: "רמת הגולן", en: "Golan Heights" },
  bio: {
    he: "גילעד יוצר כלי קרמיקה בשריפת עצים ממושכת בתנור אנאגאמה ברמת הגולן. האפר והלהבות מותירים רשמים ייחודיים.",
    en: "Gilad fires ceramics in an Anagama wood kiln in the Golan Heights.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80",
};

const orlyMizrachi: Artist = {
  slug: "orly-mizrachi",
  displayName: { he: "אורלי מזרחי", en: "Orly Mizrachi" },
  location: { he: "רחובות", en: "Rehovot" },
  bio: {
    he: "אורלי יוצרת עבודות טקסטיל תלת-ממדיות בשילוב רקמה ידנית, ליבוד צמר וחוטי כותנה מוזהבים.",
    en: "Orly creates 3D textile artwork combining embroidery and felting.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80",
};

const hadarShachar: Artist = {
  slug: "hadar-shachar",
  displayName: { he: "הדר שחר", en: "Hadar Shachar" },
  location: { he: "נס ציונה", en: "Ness Ziona" },
  bio: {
    he: "הדר מעצבת חפצי יודאיקה עכשווית מבטון אדריכלי, פליז מוברש ועץ אלון.",
    en: "Hadar designs contemporary Judaica from architectural concrete and brass.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80",
};

const arielWeinberg: Artist = {
  slug: "ariel-weinberg",
  displayName: { he: "אריאל ויינברג", en: "Ariel Weinberg" },
  location: { he: "הרצליה", en: "Herzliya" },
  bio: {
    he: "אריאל מציירת בסגנון אקספרסיבי מופשט בשכבות שמן עבות ובטכניקת סכין ציור.",
    en: "Ariel paints abstract expressionism using palette knife techniques.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
};

const netaShor: Artist = {
  slug: "neta-shor",
  displayName: { he: "נטע שור", en: "Neta Shor" },
  location: { he: "כפר סבא", en: "Kfar Saba" },
  bio: {
    he: "נטע יוצרת ספלים, קערות וכלי הגשה מפורצלן עדין בטכניקת האבניים ובצבעוניות פסטלית רכה.",
    en: "Neta throws delicate porcelain mugs and bowls on the wheel.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
};

const guyStern: Artist = {
  slug: "guy-stern",
  displayName: { he: "גיא שטרן", en: "Guy Stern" },
  location: { he: "הוד השרון", en: "Hod HaSharon" },
  bio: {
    he: "גיא מחרט ומגלף חפצי עץ שימושיים מעצי ברוש, שיזף ואורן שנאספו לאחר גזם מקומי.",
    en: "Guy carves functional wooden objects from salvaged local timber.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&q=80",
};

const roeyAloni: Artist = {
  slug: "roey-aloni",
  displayName: { he: "רועי אלוני", en: "Roey Aloni" },
  location: { he: "ראש פינה", en: "Rosh Pinna" },
  bio: {
    he: "רועי מפסל באבן בזלת גלילית קשה ובאלמנטים מנחושת מלוטשת בטכניקת סתתות ידנית.",
    en: "Roey sculpts Galilean basalt stone and polished copper elements.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
};

const michaelKraus: Artist = {
  slug: "michael-kraus",
  displayName: { he: "מיכאל קראוס", en: "Michael Kraus" },
  location: { he: "נהריה", en: "Nahariya" },
  bio: {
    he: "מיכאל יוצר הדפסי מונטייפ ותחריטים במהדורות מוגבלות בהשראת חופי הגליל המערבי והים התיכון.",
    en: "Michael creates monotype prints and limited edition etchings inspired by Western Galilee shores.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80",
};

const maayanLevin: Artist = {
  slug: "maayan-levin",
  displayName: { he: "מעין לוין", en: "Maayan Levin" },
  location: { he: "אשקלון", en: "Ashkelon" },
  bio: {
    he: "מעין מעצבת שרשראות, עגילים שטוחים וצמידים מזהב 14 קראט ואבני טורמלין צבעוניות.",
    en: "Maayan designs 14k gold necklaces and earrings set with tourmaline gemstones.",
  },
  portraitPublicId: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
};

const artworks: Artwork[] = [
  // --- 5 FOUNDATIONAL ARTWORKS ---
  {
    slug: "kaarat-adama",
    title: { he: "קערת אדמה", en: "Earth Bowl" },
    story: { he: "קערה שנבנתה ביד מחומר מקומי, עם שכבות דקות של גלזורה מינרלית שנשרפו פעמיים.", en: "A hand-built bowl in local clay, with thin layers of mineral glaze fired twice." },
    materials: { he: ["חימר מקומי", "גלזורה מינרלית"], en: ["Local clay", "Mineral glaze"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 11, widthCm: 24, depthCm: 24, weightGrams: 820 },
    priceAgorot: 34000,
    shippingSizeBand: "SMALL",
    isFragile: true,
    images: [{ publicId: "/mock/earth-bowl.jpg", aspectRatio: 4 / 5, role: "primary", caption: { he: "קערת קרמיקה רחבה", en: "Broad sand-toned ceramic bowl" } }],
    artist: noaBarak,
  },
  {
    slug: "yareach-print",
    title: { he: "ירח מלא", en: "Full Moon" },
    story: { he: "הדפס רשת בשלושה צבעים על נייר כותנה 300 גרם. מהדורה מוגבלת של 25 עותקים.", en: "Three-colour screen print on 300gsm cotton paper. Limited edition of 25 copies." },
    materials: { he: ["נייר כותנה 300 גרם", "דיוני רשת"], en: ["300gsm cotton paper", "Screen inks"] },
    discipline: "painting",
    category: { he: "הדפס", en: "Print" },
    inventoryKind: "LIMITED_EDITION",
    availability: "available",
    editionSize: 25,
    editionNumber: 4,
    dimensions: { heightCm: 40, widthCm: 30, weightGrams: 150 },
    priceAgorot: 28000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "/mock/yareach-print.jpg", aspectRatio: 3 / 4, role: "primary", caption: { he: "הדפס רשת מינימליסטי", en: "Minimalist screen print" } }],
    artist: yaelStudio,
  },
  {
    slug: "gavia-etz",
    title: { he: "גביע עץ", en: "Wooden Goblet" },
    story: { he: "גביע שנחרט מענף עץ זית שנאסף לאחר גיזום מטע בגליל.", en: "A goblet turned from an olive branch collected after pruning a Galilean grove." },
    materials: { he: ["עץ זית מקומי", "שעוות דבורים"], en: ["Local olive wood", "Beeswax"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "MADE_TO_ORDER",
    availability: "available",
    leadTimeDays: 14,
    dimensions: { heightCm: 16, widthCm: 8, depthCm: 8, weightGrams: 220 },
    priceAgorot: 19000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "/mock/wooden-goblet.jpg", aspectRatio: 3 / 4, role: "primary", caption: { he: "גביע עץ זית", en: "Hand-turned olive wood goblet" } }],
    artist: danWood,
  },

  // --- CERAMICS (10 100% UNIQUE ITEMS) ---
  {
    slug: "art-ceramics-vessel-galilee",
    title: { he: "כד גלים כחול", en: "Galilee Blue Vessel" },
    story: { he: "כד פיסולי שנבנה בטכניקת משטחים וצופה בגלזורת אוקיינוס עמוקה.", en: "Sculptural vessel slab-built and glazed in deep ocean blue." },
    materials: { he: ["חימר אפור", "גלזורה כחולה"], en: ["Grey clay", "Blue glaze"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 32, widthCm: 18, weightGrams: 1400 },
    priceAgorot: 46000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "כד קרמיקה כחול", en: "Blue ceramic vessel" } }],
    artist: michalAlon,
  },
  {
    slug: "art-ceramics-speckled-mug",
    title: { he: "ספל פורצלן מנוקד", en: "Speckled Porcelain Cup" },
    story: { he: "ספל קפה בעבודת אבניים מפורצלן לבן עם נקודות ברונזה טבעיות.", en: "Wheel-thrown porcelain mug with natural bronze speckles." },
    materials: { he: ["פורצלן לבן", "גלזורה שקופה"], en: ["White porcelain", "Clear glaze"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "LIMITED_EDITION",
    editionSize: 15,
    editionNumber: 3,
    availability: "available",
    dimensions: { heightCm: 10, widthCm: 9, weightGrams: 280 },
    priceAgorot: 15000,
    shippingSizeBand: "SMALL",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "ספל פורצלן מנוקד", en: "Speckled porcelain mug" } }],
    artist: netaShor,
  },
  {
    slug: "art-ceramics-tall-raku-vase",
    title: { he: "אגרטל ראקו מדברי", en: "Tall Desert Raku Vase" },
    story: { he: "אגרטל גבוה שנשרף בשריפת עשן ראקו חופשית במצפה רמון.", en: "Tall vase smoke-fired in free Raku style in Mitzpe Ramon." },
    materials: { he: ["חמר אדום", "עשן מינרלי"], en: ["Red clay", "Mineral smoke"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 42, widthCm: 16, weightGrams: 2100 },
    priceAgorot: 58000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1576020688413-40a2a194917a?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.55, role: "primary", caption: { he: "אגרטל ראקו גבוה", en: "Tall Raku vase" } }],
    artist: adiNavon,
  },
  {
    slug: "art-ceramics-wide-platter",
    title: { he: "מגש קרמיקה מרובע", en: "Square Sculptural Platter" },
    story: { he: "מגש הגשה שטוח בגלזורת חול מוברשת למרכז שולחן.", en: "Flat square serving platter in brushed sand glaze." },
    materials: { he: ["חימר לבן"], en: ["White clay"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 4, widthCm: 34, depthCm: 34, weightGrams: 1800 },
    priceAgorot: 39000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.33, role: "primary", caption: { he: "מגש קרמיקה מרובע", en: "Square ceramic platter" } }],
    artist: giladOren,
  },
  {
    slug: "art-ceramics-terracotta-jar",
    title: { he: "כד טרקוטה גלילי", en: "Galilean Terracotta Jar" },
    story: { he: "כד טרקוטה גולמי שנשרף בתנור עצים ממושך ברמת הגולן.", en: "Raw terracotta jar wood-fired in Golan Heights kiln." },
    materials: { he: ["טרקוטה מקומית"], en: ["Local terracotta"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 26, widthCm: 20, weightGrams: 1650 },
    priceAgorot: 42000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1530982011887-3cc11cc85693?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.85, role: "primary", caption: { he: "כד טרקוטה", en: "Terracotta jar" } }],
    artist: giladOren,
  },
  {
    slug: "art-ceramics-pitcher",
    title: { he: "קנה קרמיקה נורדי", en: "Nordic Clay Pitcher" },
    story: { he: "קנה מים פיסולי בקו נקי ומינימליסטי בגלזורת מט סלדון.", en: "Sculptural water pitcher in clean minimalist celadon matte glaze." },
    materials: { he: ["פורצלן אפור"], en: ["Grey porcelain"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "MADE_TO_ORDER",
    leadTimeDays: 10,
    availability: "available",
    dimensions: { heightCm: 24, widthCm: 14, weightGrams: 950 },
    priceAgorot: 32000,
    shippingSizeBand: "SMALL",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.7, role: "primary", caption: { he: "קנה קרמיקה", en: "Clay pitcher" } }],
    artist: michalAlon,
  },
  {
    slug: "art-ceramics-earthenware-bowl",
    title: { he: "קערת חמר מקומית", en: "Earthenware Craft Bowl" },
    story: { he: "קערת חמר אדום בטקסטורת אבניים גולמית.", en: "Red earthenware bowl with raw wheel texture." },
    materials: { he: ["חמר אדום מקומי"], en: ["Local red clay"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 12, widthCm: 22, weightGrams: 750 },
    priceAgorot: 24000,
    shippingSizeBand: "SMALL",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1574634534894-89d7576c8259?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.25, role: "primary", caption: { he: "קערת חמר מקומית", en: "Earthenware bowl" } }],
    artist: noaBarak,
  },
  {
    slug: "art-ceramics-stoneware-pot",
    title: { he: "סיר סטודיו מסטונור", en: "Studio Stoneware Pot" },
    story: { he: "כלי סטודיו כבד מסטונור בשריפת צמצום בתנור גז.", en: "Heavy studio stoneware vessel gas-fired in reduction." },
    materials: { he: ["סטונור אפור"], en: ["Grey stoneware"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 28, widthCm: 19, weightGrams: 1900 },
    priceAgorot: 45000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1525974160448-038dacadcc71?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.65, role: "primary", caption: { he: "כלי סטונור", en: "Stoneware pot" } }],
    artist: giladOren,
  },
  {
    slug: "art-ceramics-glazed-pot",
    title: { he: "סיר חמר עם גלזורה ירוקה", en: "Green Glazed Clay Pot" },
    story: { he: "כלי חמר עגול בגלזורה ירוקה-זית עמוקה.", en: "Round clay pot in deep olive-green glaze." },
    materials: { he: ["חימר אדום", "גלזורה ירוקה"], en: ["Red clay", "Green glaze"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 18, widthCm: 18, weightGrams: 1100 },
    priceAgorot: 28000,
    shippingSizeBand: "SMALL",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.8, role: "primary", caption: { he: "סיר חמר ירוק", en: "Green glazed clay pot" } }],
    artist: michalAlon,
  },
  {
    slug: "art-ceramics-terracotta-salad-bowl",
    title: { he: "קערת סלט טרקוטה", en: "Terracotta Salad Bowl" },
    story: { he: "קערת הגשה רחבה בטקסטורת טרקוטה גולמית ושפת מלח.", en: "Broad serving bowl with raw terracotta texture and salt rim." },
    materials: { he: ["טרקוטה מקומית"], en: ["Local terracotta"] },
    discipline: "ceramics",
    category: { he: "קרמיקה", en: "Ceramics" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 8, widthCm: 30, weightGrams: 1200 },
    priceAgorot: 31000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.4, role: "primary", caption: { he: "קערת טרקוטה", en: "Terracotta salad bowl" } }],
    artist: noaBarak,
  },

  // --- JEWELRY (9 100% UNIQUE ITEMS) ---
  {
    slug: "art-jewelry-gold-raw-ring",
    title: { he: "טבעת זהב וטורמלין גולמי", en: "Gold & Raw Tourmaline Ring" },
    story: { he: "טבעת זהב 14 קראט בטקסטורת פטיש משובצת אבן טורמלין ירוקה גולמית.", en: "14k gold ring with hammered texture set with raw green tourmaline." },
    materials: { he: ["זהב 14 קראט", "טורמלין גולמי"], en: ["14k gold", "Raw tourmaline"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 2, widthCm: 2, weightGrams: 8 },
    priceAgorot: 49000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "טבעת זהב וטורמלין", en: "Gold & tourmaline ring" } }],
    artist: doritShacham,
  },
  {
    slug: "art-jewelry-silver-pendant",
    title: { he: "תליון כסף גיאומטרי", en: "Geometric Silver Pendant" },
    story: { he: "תליון כסף סטרלינג 925 פיסולי בגימור מט מוברש.", en: "Sculptural 925 sterling silver pendant in brushed matte finish." },
    materials: { he: ["כסף סטרלינג 925"], en: ["925 Sterling silver"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "LIMITED_EDITION",
    editionSize: 10,
    editionNumber: 2,
    availability: "available",
    dimensions: { heightCm: 4, widthCm: 3, weightGrams: 15 },
    priceAgorot: 29000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.8, role: "primary", caption: { he: "תליון כסף", en: "Silver pendant" } }],
    artist: anatShapira,
  },
  {
    slug: "art-jewelry-gold-drop-earrings",
    title: { he: "עגילי זהב מוברש", en: "Brushed Gold Drop Earrings" },
    story: { he: "עגילי תלייה קלילים מזהב 18 קראט בצורת עלה מופשט.", en: "Lightweight 18k gold drop earrings in an abstract leaf shape." },
    materials: { he: ["זהב 18 קראט"], en: ["18k gold"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 5, widthCm: 1.5, weightGrams: 6 },
    priceAgorot: 38000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "עגילי זהב", en: "Gold drop earrings" } }],
    artist: maayanLevin,
  },
  {
    slug: "art-jewelry-brass-bangle",
    title: { he: "צמיד פליז פיסולי", en: "Sculptural Brass Bangle" },
    story: { he: "צמיד פליז עבה שחושק ורוקע ביד בסטודיו בבאר שבע.", en: "Hand-forged thick brass bangle crafted in Be'er Sheva." },
    materials: { he: ["פליז מוברש"], en: ["Brushed brass"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 7, widthCm: 7, weightGrams: 45 },
    priceAgorot: 22000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1611591475179-c5c8e3100650?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.1, role: "primary", caption: { he: "צמיד פליז", en: "Brass bangle" } }],
    artist: liorBenDavid,
  },
  {
    slug: "art-jewelry-gold-choker",
    title: { he: "שרשרת זהב מוברש", en: "Brushed Gold Collar" },
    story: { he: "שרשרת קולר קשיחה מזהב 14 קראט בגימור מט יוקרתי.", en: "Rigid 14k gold collar necklace in luxury matte finish." },
    materials: { he: ["זהב 14 קראט"], en: ["14k gold"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 15, widthCm: 15, weightGrams: 28 },
    priceAgorot: 78000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.85, role: "primary", caption: { he: "שרשרת זהב", en: "Gold collar" } }],
    artist: doritShacham,
  },
  {
    slug: "art-jewelry-turquoise-ring",
    title: { he: "טבעת כסף וטורקיז", en: "Silver & Turquoise Ring" },
    story: { he: "טבעת כסף מרוקעת משובצת אבן טורקיז טבעית מחצי האי סיני.", en: "Hammered silver ring set with natural turquoise stone." },
    materials: { he: ["כסף סטרלינג 925", "טורקיז טבעי"], en: ["925 Silver", "Natural turquoise"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 2.5, widthCm: 2, weightGrams: 11 },
    priceAgorot: 26000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "טבעת טורקיז", en: "Turquoise ring" } }],
    artist: anatShapira,
  },
  {
    slug: "art-jewelry-pearl-studs",
    title: { he: "עגילי פנינה וזהב", en: "Pearl & Gold Stud Earrings" },
    story: { he: "עגילי צמודים מזהב 14 קראט משובצים פניני מים מתוקים.", en: "14k gold stud earrings set with freshwater pearls." },
    materials: { he: ["זהב 14 קראט", "פנינה טבעית"], en: ["14k gold", "Freshwater pearl"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 1.2, widthCm: 1.2, weightGrams: 3 },
    priceAgorot: 21000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.9, role: "primary", caption: { he: "עגילי פנינה", en: "Pearl stud earrings" } }],
    artist: maayanLevin,
  },
  {
    slug: "art-jewelry-silver-cuffs",
    title: { he: "צמיד כסף פיסולי", en: "Sculptural Silver Cuff" },
    story: { he: "צמיד כסף סטרלינג רחב בעל טקסטורת אדמה מוברשת.", en: "Wide 925 sterling silver cuff with brushed earth texture." },
    materials: { he: ["כסף סטרלינג 925"], en: ["925 Silver"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 6, widthCm: 6.5, weightGrams: 52 },
    priceAgorot: 45000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.15, role: "primary", caption: { he: "צמיד כסף", en: "Silver cuff" } }],
    artist: anatShapira,
  },
  {
    slug: "art-jewelry-silver-band",
    title: { he: "טבעת כסף מינימליסטית", en: "Minimalist Silver Band Ring" },
    story: { he: "טבעת כסף עבה בגימור מט נקי.", en: "Thick sterling silver band ring in clean matte finish." },
    materials: { he: ["כסף סטרלינג 925"], en: ["925 Silver"] },
    discipline: "jewelry",
    category: { he: "תכשיטים", en: "Jewelry" },
    inventoryKind: "LIMITED_EDITION",
    editionSize: 15,
    editionNumber: 6,
    availability: "available",
    dimensions: { heightCm: 1.8, widthCm: 1.8, weightGrams: 7 },
    priceAgorot: 18000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.2, role: "primary", caption: { he: "טבעת כסף", en: "Silver band ring" } }],
    artist: anatShapira,
  },

  // --- PAINTING & PRINT (10 100% UNIQUE ITEMS) ---
  {
    slug: "art-painting-galilee-fields",
    title: { he: "שדות גליל בשקיעה", en: "Galilee Fields at Sunset" },
    story: { he: "ציור שמן פיגורטיבי-מופשט המבטא את אור השקיעה מעל שדות פשתן.", en: "Figurative abstract oil painting reflecting sunset light over Galilee fields." },
    materials: { he: ["שמן על קנווס פשתן"], en: ["Oil on linen canvas"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 90, widthCm: 70, weightGrams: 2800 },
    priceAgorot: 195000,
    shippingSizeBand: "LARGE",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "ציור שמן גלילי", en: "Galilee oil painting" } }],
    artist: shiraLevi,
  },
  {
    slug: "art-painting-desert-horizon",
    title: { he: "אור מכתש פנורמי", en: "Panoramic Crater Light" },
    story: { he: "קומפוזיציה רחבה ואופקית בגווני אוקר, זהב וחול מדברי.", en: "Wide horizontal composition in ochre, gold, and desert sand." },
    materials: { he: ["אקריליק ושמן על בד"], en: ["Acrylic and oil on canvas"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 60, widthCm: 140, weightGrams: 3400 },
    priceAgorot: 260000,
    shippingSizeBand: "LARGE",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.6, role: "primary", caption: { he: "ציור מדברי פנורמי", en: "Panoramic desert painting" } }],
    artist: arielWeinberg,
  },
  {
    slug: "art-painting-abstract-layers",
    title: { he: "שכבות מופשטות #12", en: "Abstract Layers #12" },
    story: { he: "עבודת אקריליק עשירת מרקם בטכניקת סכין ציור ושכבות צבע עבות.", en: "Texture-rich acrylic work created with palette knife technique." },
    materials: { he: ["אקריליק על קנווס"], en: ["Acrylic on canvas"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 80, widthCm: 80, weightGrams: 2200 },
    priceAgorot: 155000,
    shippingSizeBand: "LARGE",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "ציור מופשט מרובע", en: "Square abstract painting" } }],
    artist: arielWeinberg,
  },
  {
    slug: "art-painting-watercolor-coast",
    title: { he: "קו חוף חיפה בצבעי מים", en: "Haifa Coastline Watercolor" },
    story: { he: "ציור צבעי מים עדין ומלא אור על נייר ארש כבד 300 גרם.", en: "Light-filled watercolor painting on heavy 300gsm Arches paper." },
    materials: { he: ["צבעי מים על נייר ארש"], en: ["Watercolor on Arches paper"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 50, widthCm: 35, weightGrams: 300 },
    priceAgorot: 88000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.67, role: "primary", caption: { he: "ציור צבעי מים", en: "Watercolor painting" } }],
    artist: roniKatz,
  },
  {
    slug: "art-painting-linocut-botanical",
    title: { he: "הדפס לינולאום גלילי", en: "Galilee Botanical Linocut" },
    story: { he: "הדפס לינולאום ידני במהדורה מוגבלת של 20 עותקים חתומים.", en: "Handmade linocut print in a limited edition of 20 signed copies." },
    materials: { he: ["נייר כותנה", "דיור לינולאום"], en: ["Cotton paper", "Linocut ink"] },
    discipline: "painting",
    category: { he: "הדפס", en: "Print" },
    inventoryKind: "LIMITED_EDITION",
    editionSize: 20,
    editionNumber: 5,
    availability: "available",
    dimensions: { heightCm: 45, widthCm: 35, weightGrams: 180 },
    priceAgorot: 31000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.8, role: "primary", caption: { he: "הדפס לינולאום", en: "Linocut print" } }],
    artist: michaelKraus,
  },
  {
    slug: "art-painting-textured-canvas",
    title: { he: "טקסטורת אדמה ואוקיינוס", en: "Earth & Ocean Texture" },
    story: { he: "ציור מופשט בשכבות אקריליק מוברש עם פיגמנטים טבעיים.", en: "Abstract painting in brushed acrylic layers with natural pigments." },
    materials: { he: ["אקריליק ופיגמנטים"], en: ["Acrylic & pigments"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 70, widthCm: 90, weightGrams: 2600 },
    priceAgorot: 170000,
    shippingSizeBand: "LARGE",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1578926375705-90ae2442431d?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.25, role: "primary", caption: { he: "ציור מופשט רחב", en: "Wide abstract painting" } }],
    artist: shiraLevi,
  },
  {
    slug: "art-painting-landscape-study",
    title: { he: "רישום נוף שמן", en: "Oil Landscape Study" },
    story: { he: "רישום שמן מהיר מהטבע בגליל העליון.", en: "Plein air oil study from Upper Galilee nature." },
    materials: { he: ["שמן על לוח עץ"], en: ["Oil on wood panel"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 35, widthCm: 25, weightGrams: 450 },
    priceAgorot: 62000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.7, role: "primary", caption: { he: "רישום שמן", en: "Oil landscape study" } }],
    artist: shiraLevi,
  },
  {
    slug: "art-painting-modernist-print",
    title: { he: "הדפס מודרניסטי", en: "Modernist Graphic Art Print" },
    story: { he: "הדפס רשת במהדורה מוגבלת של 30 עותקים חתומים.", en: "Limited edition screen print of 30 signed copies." },
    materials: { he: ["נייר כותנה 300 גרם"], en: ["300gsm Cotton paper"] },
    discipline: "painting",
    category: { he: "הדפס", en: "Print" },
    inventoryKind: "LIMITED_EDITION",
    editionSize: 30,
    editionNumber: 8,
    availability: "available",
    dimensions: { heightCm: 50, widthCm: 70, weightGrams: 280 },
    priceAgorot: 36000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.33, role: "primary", caption: { he: "הדפס מודרניסטי", en: "Modernist art print" } }],
    artist: yaelStudio,
  },
  {
    slug: "art-painting-ink-sketch",
    title: { he: "רישום דיו מינימליסטי", en: "Minimalist Ink Sketch" },
    story: { he: "רישום דיו יפני במברשת אחת על נייר אורז.", en: "Minimalist Japanese ink brush sketch on rice paper." },
    materials: { he: ["דיו שחור", "נייר אורז"], en: ["Black ink", "Rice paper"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 40, widthCm: 30, weightGrams: 120 },
    priceAgorot: 45000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.85, role: "primary", caption: { he: "רישום דיו", en: "Minimalist ink sketch" } }],
    artist: michaelKraus,
  },
  {
    slug: "art-painting-gradient-canvas",
    title: { he: "קנווס מופשט אופקי", en: "Horizontal Gradient Canvas" },
    story: { he: "ציור אקריליק רחב במעברי צבע עדינים.", en: "Wide acrylic painting in smooth color gradients." },
    materials: { he: ["אקריליק על קנווס"], en: ["Acrylic on canvas"] },
    discipline: "painting",
    category: { he: "ציור", en: "Painting" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 60, widthCm: 90, weightGrams: 2100 },
    priceAgorot: 140000,
    shippingSizeBand: "LARGE",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.5, role: "primary", caption: { he: "ציור מופשט אופקי", en: "Horizontal gradient canvas" } }],
    artist: arielWeinberg,
  },

  // --- WOODWORK (7 100% UNIQUE ITEMS) ---
  {
    slug: "art-wood-sculptural-olive-bowl",
    title: { he: "קערת עץ זית פיסולית", en: "Sculptural Olive Wood Bowl" },
    story: { he: "קערת הגשה שנחרטה מגוש עץ זית עתיק בן מאות שנים בגלבוע.", en: "Serving bowl turned from centuries-old olive wood block." },
    materials: { he: ["עץ זית עתיק", "שמן חריע"], en: ["Ancient olive wood", "Safflower oil"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 14, widthCm: 32, weightGrams: 1450 },
    priceAgorot: 64000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.33, role: "primary", caption: { he: "קערת עץ זית", en: "Olive wood bowl" } }],
    artist: yuvalArad,
  },
  {
    slug: "art-wood-walnut-board",
    title: { he: "לוח הגשה מעץ אגוז", en: "Walnut Wood Serving Board" },
    story: { he: "לוח הגשה וחיתוך מעץ אגוז אמריקאי בעל סיבים טבעיים עשירים.", en: "Serving board handcrafted from American walnut with rich natural grain." },
    materials: { he: ["עץ אגוז", "שעוות טבעית"], en: ["Walnut wood", "Natural wax"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "MADE_TO_ORDER",
    leadTimeDays: 7,
    availability: "available",
    dimensions: { heightCm: 3, widthCm: 45, depthCm: 25, weightGrams: 1200 },
    priceAgorot: 34000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1546484475-7f7bd55792da?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "לוח עץ אגוז", en: "Walnut board" } }],
    artist: danWood,
  },
  {
    slug: "art-wood-oak-sculpture",
    title: { he: "פסל עץ אלון ממוחזר", en: "Reclaimed Oak Wood Sculpture" },
    story: { he: "פסל דקורטיבי שנחרט מעץ אלון ממוחזר בגימור מט חלק.", en: "Decorative sculpture carved from reclaimed oak wood." },
    materials: { he: ["עץ אלון ממוחזר"], en: ["Reclaimed oak"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 38, widthCm: 16, weightGrams: 2100 },
    priceAgorot: 89000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "פסל עץ אלון", en: "Oak wood sculpture" } }],
    artist: guyStern,
  },
  {
    slug: "art-wood-turned-vase",
    title: { he: "אגרטל עץ ברוש חרוט", en: "Turned Cypress Wood Vase" },
    story: { he: "אגרטל עץ יבש שנחרט מגזע ברוש מקומי שנאסף לאחר גזם.", en: "Dry wood vase turned from a local cypress log." },
    materials: { he: ["עץ ברוש מקומי"], en: ["Local cypress wood"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 28, widthCm: 14, weightGrams: 980 },
    priceAgorot: 48000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.8, role: "primary", caption: { he: "אגרטל עץ ברוש", en: "Cypress wood vase" } }],
    artist: guyStern,
  },
  {
    slug: "art-wood-natural-edge-vessel",
    title: { he: "כד עץ פראי", en: "Natural Edge Wood Vessel" },
    story: { he: "כד עץ זית עם שפה פראית וטבעית המשמרת את קליפת העץ.", en: "Olive wood vessel with a wild natural live edge preserving bark." },
    materials: { he: ["עץ זית פראי"], en: ["Live edge olive wood"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 22, widthCm: 26, weightGrams: 1600 },
    priceAgorot: 69000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.2, role: "primary", caption: { he: "כד עץ פראי", en: "Live edge wood vessel" } }],
    artist: yuvalArad,
  },
  {
    slug: "art-wood-rustic-bowl",
    title: { he: "קערת עץ כפרית", en: "Rustic Carved Wooden Bowl" },
    story: { he: "קערה עמוקה בעבודת גילוף ידנית ממיזוף מקומי.", en: "Deep bowl hand-carved from local jujube wood." },
    materials: { he: ["עץ שיזף"], en: ["Jujube wood"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 12, widthCm: 24, weightGrams: 890 },
    priceAgorot: 36000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.9, role: "primary", caption: { he: "קערת עץ כפרית", en: "Rustic wooden bowl" } }],
    artist: guyStern,
  },
  {
    slug: "art-wood-box",
    title: { he: "תיבת עץ אלון מעוצבת", en: "Handcrafted Oak Wooden Box" },
    story: { he: "תיבה קטנה עם מכסה תואם בעבודת חרטות ונגרות אומן.", en: "Small keepsake box with fitted lid turned from solid oak." },
    materials: { he: ["עץ אלון גלילי"], en: ["Solid Galilean oak"] },
    discipline: "wood",
    category: { he: "עץ", en: "Wood" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 10, widthCm: 18, depthCm: 12, weightGrams: 620 },
    priceAgorot: 31000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.1, role: "primary", caption: { he: "תיבת עץ אלון", en: "Oak wooden box" } }],
    artist: danWood,
  },

  // --- SCULPTURE (6 100% UNIQUE ITEMS) ---
  {
    slug: "art-sculpture-bronze-organic",
    title: { he: "פסל ברונזה אורגני", en: "Organic Bronze Figurine" },
    story: { he: "פסל ברונזה יצוקה בעבודת יד במהדורה מוגבלת של 8 עותקים בלבד.", en: "Hand-cast bronze figurine in a limited edition of 8 pieces." },
    materials: { he: ["ברונזה יצוקה"], en: ["Cast bronze"] },
    discipline: "sculpture",
    category: { he: "פיסול", en: "Sculpture" },
    inventoryKind: "LIMITED_EDITION",
    editionSize: 8,
    editionNumber: 2,
    availability: "available",
    dimensions: { heightCm: 22, widthCm: 15, weightGrams: 3200 },
    priceAgorot: 320000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "פסל ברונזה", en: "Bronze sculpture" } }],
    artist: itamarGoldstein,
  },
  {
    slug: "art-sculpture-limestone-carving",
    title: { he: "פיסול אבן גלילית", en: "Galilean Limestone Carving" },
    story: { he: "עבודת סתתות ידנית באבן גיר גלילית בעלת טקסטורת מאובנים טבעית.", en: "Manual stone carving in Galilean limestone featuring natural fossils." },
    materials: { he: ["אבן גיר גלילית"], en: ["Galilean limestone"] },
    discipline: "sculpture",
    category: { he: "פיסול", en: "Sculpture" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 30, widthCm: 25, weightGrams: 6500 },
    priceAgorot: 280000,
    shippingSizeBand: "LARGE",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1554188248-986adbb73be4?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.8, role: "primary", caption: { he: "פיסול אבן גיר", en: "Limestone sculpture" } }],
    artist: itamarGoldstein,
  },
  {
    slug: "art-sculpture-basalt-form",
    title: { he: "פסל בזלת ונחושת", en: "Basalt & Copper Structure" },
    story: { he: "פסל סביבתי קטן המשלב אבן בזלת גלילית קשה עם נחושת מלוטשת.", en: "Sculpture combining hard Galilean basalt stone with polished copper." },
    materials: { he: ["אבן בזלת", "נחושת מלוטשת"], en: ["Basalt stone", "Polished copper"] },
    discipline: "sculpture",
    category: { he: "פיסול", en: "Sculpture" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 35, widthCm: 18, weightGrams: 4800 },
    priceAgorot: 310000,
    shippingSizeBand: "LARGE",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1569091791842-7cfb64e04797?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.67, role: "primary", caption: { he: "פסל בזלת ונחושת", en: "Basalt & copper sculpture" } }],
    artist: roeyAloni,
  },
  {
    slug: "art-sculpture-clay-totem",
    title: { he: "טוטם חמר מינימליסטי", en: "Minimalist Clay Totem" },
    story: { he: "פסל חמר גולמי תלת-ממדי בטקסטורת אדמה חשופה.", en: "Raw 3D clay totem sculpture with exposed earth texture." },
    materials: { he: ["חמר גולמי"], en: ["Raw clay"] },
    discipline: "sculpture",
    category: { he: "פיסול", en: "Sculpture" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 48, widthCm: 14, weightGrams: 2900 },
    priceAgorot: 180000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1561839561-b13bcfe95249?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.55, role: "primary", caption: { he: "טוטם חמר", en: "Clay totem sculpture" } }],
    artist: itamarGoldstein,
  },
  {
    slug: "art-sculpture-terracotta-bust",
    title: { he: "דיוקן חמר אדום", en: "Terracotta Head Study" },
    story: { he: "פיסול דיוקן מופשט בחמר אדום מקומי.", en: "Abstract terracotta head study sculptured in red clay." },
    materials: { he: ["חמר אדום"], en: ["Red clay"] },
    discipline: "sculpture",
    category: { he: "פיסול", en: "Sculpture" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 26, widthCm: 18, weightGrams: 2400 },
    priceAgorot: 160000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.85, role: "primary", caption: { he: "דיוקן חמר", en: "Terracotta head study" } }],
    artist: itamarGoldstein,
  },
  {
    slug: "art-sculpture-marble-wood",
    title: { he: "מבנה שיש ועץ", en: "Marble & Wood Form" },
    story: { he: "פסל שולחני המשלב אבן שיש לבנה עם עץ אגוז.", en: "Desktop sculpture combining white marble stone with walnut wood." },
    materials: { he: ["שיש לבן", "עץ אגוז"], en: ["White marble", "Walnut wood"] },
    discipline: "sculpture",
    category: { he: "פיסול", en: "Sculpture" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 25, widthCm: 16, weightGrams: 3100 },
    priceAgorot: 220000,
    shippingSizeBand: "MEDIUM",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.95, role: "primary", caption: { he: "פסל שיש ועץ", en: "Marble & wood sculpture" } }],
    artist: itamarGoldstein,
  },

  // --- TEXTILE & FIBER ART (4 100% UNIQUE ITEMS) ---
  {
    slug: "art-textile-tapestry",
    title: { he: "שטיח קיר צמר ישראלי", en: "Israeli Wool Wall Tapestry" },
    story: { he: "אריגת יד עשירה בטקסטורות מכותנה וצמר כבשים ישראלי על נול עץ.", en: "Hand-woven wall tapestry rich in textures from Israeli wool on wooden loom." },
    materials: { he: ["צמר כבשים", "חוטי כותנה"], en: ["Sheep's wool", "Cotton yarn"] },
    discipline: "textile",
    category: { he: "טקסטיל", en: "Textile" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 110, widthCm: 65, weightGrams: 1400 },
    priceAgorot: 125000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1606744888344-493238951221?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.33, role: "primary", caption: { he: "שטיח קיר צמר", en: "Wool wall tapestry" } }],
    artist: tamarFriedman,
  },
  {
    slug: "art-textile-felt-art",
    title: { he: "תמונת ליבוד וחוטי זהב", en: "Wool Felt & Gold Thread Art" },
    story: { he: "עבודת ליבוד צמר ורקמת חוטי זהב עדינה במסגרת עץ אלון.", en: "Wool felt and gold thread embroidery framed in natural oak wood." },
    materials: { he: ["ליבוד צמר", "חוטי זהב"], en: ["Wool felt", "Gold thread"] },
    discipline: "textile",
    category: { he: "טקסטיל", en: "Textile" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 45, widthCm: 45, weightGrams: 850 },
    priceAgorot: 85000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "תמונת ליבוד", en: "Felt textile art" } }],
    artist: orlyMizrachi,
  },
  {
    slug: "art-textile-linen-hanging",
    title: { he: "מתלה פשתן טבעי", en: "Natural Linen Wall Hanging" },
    story: { he: "מתלה פשתן גולמי בטקסטורות אריגה ידניות רכות.", en: "Raw linen wall hanging with soft hand-woven textures." },
    materials: { he: ["פשתן גולמי", "עץ אלון"], en: ["Raw linen", "Oak wood"] },
    discipline: "textile",
    category: { he: "טקסטיל", en: "Textile" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 95, widthCm: 40, weightGrams: 600 },
    priceAgorot: 68000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1528458876861-544fd1761a91?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "מתלה פשתן", en: "Linen wall hanging" } }],
    artist: tamarFriedman,
  },
  {
    slug: "art-textile-macrame-sculpture",
    title: { he: "פיסול סיבים במקרמה", en: "Macrame Fiber Wall Sculpture" },
    story: { he: "עבודת מקרמה פיסולית עשירה בקשרים ידניים מחוטי כותנה טבעית.", en: "Sculptural macrame wall piece rich in hand knots." },
    materials: { he: ["חוטי כותנה טבעית"], en: ["Natural cotton cord"] },
    discipline: "textile",
    category: { he: "טקסטיל", en: "Textile" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 120, widthCm: 50, weightGrams: 1100 },
    priceAgorot: 92000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1509319117193-57bab727e09d?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.6, role: "primary", caption: { he: "פיסול מקרמה", en: "Macrame fiber sculpture" } }],
    artist: orlyMizrachi,
  },

  // --- JUDAICA (5 100% UNIQUE ITEMS) ---
  {
    slug: "art-judaica-candlesticks",
    title: { he: "פמוטי כסף מרוקעים", en: "Hammered Sterling Silver Candlesticks" },
    story: { he: "זוג פמוטי שבת בריקוע פטיש ידני ומסורתי ברובע היהודי בירושלים.", en: "Pair of Shabbat candlesticks with traditional hand hammering in Jerusalem." },
    materials: { he: ["כסף טהור 925"], en: ["925 Fine silver"] },
    discipline: "judaica",
    category: { he: "יודאיקה", en: "Judaica" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 22, widthCm: 10, weightGrams: 480 },
    priceAgorot: 175000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.33, role: "primary", caption: { he: "פמוטי כסף", en: "Silver candlesticks" } }],
    artist: avnerCohen,
  },
  {
    slug: "art-judaica-concrete-mezuzah",
    title: { he: "מזוזת בטון ופליז", en: "Architectural Concrete Mezuzah" },
    story: { he: "מזוזה בעיצוב ארכיטקטוני נקי מבטון מוברש ופליז מוזהב.", en: "Architectural mezuzah crafted from concrete and gold brass." },
    materials: { he: ["בטון אדריכלי", "פליז מוברש"], en: ["Architectural concrete", "Brushed brass"] },
    discipline: "judaica",
    category: { he: "יודאיקה", en: "Judaica" },
    inventoryKind: "MADE_TO_ORDER",
    leadTimeDays: 5,
    availability: "available",
    dimensions: { heightCm: 14, widthCm: 3, weightGrams: 190 },
    priceAgorot: 28000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.0, role: "primary", caption: { he: "מזוזת בטון", en: "Concrete mezuzah" } }],
    artist: hadarShachar,
  },
  {
    slug: "art-judaica-kiddush-cup",
    title: { he: "גביע קידוש קרמי", en: "Ceramic Kiddush Cup" },
    story: { he: "גביע קידוש עדין בעבודת אבניים בגלזורת לבן פנינה מוברשת.", en: "Delicate wheel-thrown ceramic Kiddush cup in brushed pearl white glaze." },
    materials: { he: ["פורצלן לבן", "גלזורה מוזהבת"], en: ["White porcelain", "Golden glaze"] },
    discipline: "judaica",
    category: { he: "יודאיקה", en: "Judaica" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 13, widthCm: 7, weightGrams: 220 },
    priceAgorot: 32000,
    shippingSizeBand: "SMALL",
    isFragile: true,
    images: [{ publicId: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.75, role: "primary", caption: { he: "גביע קידוש", en: "Kiddush cup" } }],
    artist: amitRaz,
  },
  {
    slug: "art-judaica-chanukiah",
    title: { he: "חנוכיית פליז עכשווית", en: "Contemporary Brass Chanukiah" },
    story: { he: "חנוכייה פיסולית מחוט פליז מוברש בעיצוב מודרני שקט.", en: "Sculptural Chanukiah in brushed brass wire with quiet modern design." },
    materials: { he: ["פליז מוברש"], en: ["Brushed brass"] },
    discipline: "judaica",
    category: { he: "יודאיקה", en: "Judaica" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 18, widthCm: 32, weightGrams: 950 },
    priceAgorot: 89000,
    shippingSizeBand: "MEDIUM",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1000&q=80", aspectRatio: 1.4, role: "primary", caption: { he: "חנוכיית פליז", en: "Brass Chanukiah" } }],
    artist: hadarShachar,
  },
  {
    slug: "art-judaica-havdalah-set",
    title: { he: "ערכת הבדלה מעץ זית", en: "Olive Wood Havdalah Set" },
    story: { he: "סט הבדלה פיסולי מעץ זית מקומי הכולל גביע, בשמים ופמוט.", en: "Sculptural Havdalah set in local olive wood including cup, spices holder & candleholder." },
    materials: { he: ["עץ זית מקומי"], en: ["Local olive wood"] },
    discipline: "judaica",
    category: { he: "יודאיקה", en: "Judaica" },
    inventoryKind: "UNIQUE",
    availability: "available",
    dimensions: { heightCm: 18, widthCm: 25, weightGrams: 850 },
    priceAgorot: 68000,
    shippingSizeBand: "SMALL",
    isFragile: false,
    images: [{ publicId: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=80", aspectRatio: 0.85, role: "primary", caption: { he: "ערכת הבדלה", en: "Olive wood Havdalah set" } }],
    artist: yuvalArad,
  },
];

const dynamicArtworksStore: Artwork[] = [];

export function addCustomArtwork(newArtwork: Artwork): void {
  if (!dynamicArtworksStore.some((a) => a.slug === newArtwork.slug)) {
    dynamicArtworksStore.unshift(newArtwork);
  }
  try {
    if (typeof window !== "undefined") {
      const existing: Artwork[] = JSON.parse(localStorage.getItem("boby_custom_artworks") || "[]");
      if (!existing.some((a) => a.slug === newArtwork.slug)) {
        localStorage.setItem("boby_custom_artworks", JSON.stringify([newArtwork, ...existing]));
      }
    }
  } catch {
    // Ignore storage error
  }
}

function getAllArtworks(): Artwork[] {
  let custom: Artwork[] = [];
  try {
    if (typeof window !== "undefined") {
      custom = JSON.parse(localStorage.getItem("boby_custom_artworks") || "[]");
    }
  } catch {
    custom = [];
  }
  const combined = [...dynamicArtworksStore, ...custom, ...artworks];
  const uniqueMap = new Map<string, Artwork>();
  for (const item of combined) {
    if (!uniqueMap.has(item.slug)) {
      uniqueMap.set(item.slug, item);
    }
  }
  return Array.from(uniqueMap.values());
}

export async function getArtworkBySlug(slug: string): Promise<Artwork | null> {
  const all = getAllArtworks();
  return all.find((a) => a.slug === slug) ?? null;
}

export async function listArtworkSlugs(): Promise<string[]> {
  const all = getAllArtworks();
  return all.map((a) => a.slug);
}

export async function listArtworks(): Promise<Artwork[]> {
  return getAllArtworks();
}

export async function listArtistSlugs(): Promise<string[]> {
  const all = getAllArtworks();
  return [...new Set(all.map((a) => a.artist.slug))];
}

export async function getArtistBySlug(slug: string): Promise<Artist | null> {
  const all = getAllArtworks();
  return all.find((a) => a.artist.slug === slug)?.artist ?? null;
}

export async function listArtworksByArtist(slug: string): Promise<Artwork[]> {
  const all = getAllArtworks();
  return all.filter((a) => a.artist.slug === slug);
}
